app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('employee/', include('order.urls')),
    path('', include('product.urls')),
]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='employee-index'),
    path('update-item/<int:id>/', views.update_item, name='update'),
    path('add-item/', views.add_item, name='add'),
    path('import-item/', views.import_item, name='import'),
    path('delete-item/<int:id>/', views.delete_item, name='delete'),
    path('orders/', views.orders, name='orders-list'),
    path('order/<int:id>', views.detailed_order, name='orders-list'),
    path('shipping-orders/', views.shipping_orders, name='orders-list'),
    path('shipped/<int:id>', views.shipped_change, name='shipped'),
]

product/urls.py
from django.urls import path
from . import views 
urlpatterns = [
    path('', views.index, name='index'),
    path('cart/', views.cart, name='cart'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='addcart'),
    path('item/<int:id>/', views.item, name = 'item'),
    path('remove-from-cart/<int:id>/', views.remove_item, name = 'item'),
    path('comment/<int:id>/', views.rate_item, name='comment-rate'),
    path('create-order/', views.create_order, name = 'create-order'),
    path('orders/', views.view_orders, name = 'list-order'),
    path('order/<int:orderId>/', views.view_order, name = 'view-order'),
    path('report/', views.feedback, name = 'feedback'),
    path('buy-now/<int:id>/', views.buynow, name='buynow'),
    path('noti/<int:id>/', views.change_noti, name="change-notification"),
    path('onoti/<int:id>/', views.change_onoti, name="change-order-notification"),
    path('feedback-order/<int:id>/', views.feedback_order, name="feedback-order"),
    path('detail-feedback/<int:id>/', views.detail_feedback, name="feedback-order"),
]

order/models.py
from django.db import models
from django.contrib import admin
from enum import Enum
from user.models import Address, Account, Person
from product.models import Product, Supplier
# Create your models here.
class Feedback(models.Model) : 
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    content = models.TextField()
    status = models.CharField(max_length=50)
class Store(models.Model) : 
    name = models.CharField(max_length=200)
    description = models.TextField()
    address = models.CharField(max_length=200)
class Payment(models.Model) : 
    methodChoice = [('BANK' , 'BANK'), ('COD', "COD")]
    paymentDate = models.DateTimeField()
    amount = models.FloatField()
    paymentMethod = models.CharField(max_length=200, choices=methodChoice)
class Shipping(models.Model) : 
    status  = [(1 , "SHIPPING"),
    (2, "DONE"),
    (0 , "PROCESSING")]
    companyName = models.CharField(max_length=200)
    shipperName = models.CharField(max_length=200)
    shipperPhone = models.CharField(max_length=200)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    shipStatus = models.IntegerField(choices=status, default=0)
class Order(models.Model) :
    date = models.DateTimeField()
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)  
    person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True)
    shipping = models.ForeignKey(Shipping, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return 'Order ' + self.date.strftime("%d/%m/%y-%H:%M:%S")
    
class OrderLine(models.Model) :
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    unitPrice = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
class SHIP_STATUS(Enum) :
    SHIPPING = "SHIPPING"
    DONE = "DONE"
    PROCESSING = "PROCESSING"
class Event(models.Model) : 
    name = models.CharField(max_length=200)
    startDate = models.DateField()
    endDate =models.DateField()
    description = models.TextField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
class Discount(models.Model) : 
    discountRate = models.IntegerField()
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
class Warehouse(models.Model) :
    name = models.CharField(max_length=200)
    description = models.TextField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
class Notification(models.Model) : 
    description = models.TextField()
    store = models.ForeignKey(Store , on_delete=models.CASCADE) 
# Bonus
class NotificationAccount(models.Model) :
    account = models.ForeignKey(to = Account, on_delete=models.CASCADE )
    notification = models.ForeignKey(to = Notification, on_delete=models.CASCADE )
    isRead = models.BooleanField()
class ImportedProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE, null=True)
    importPrice = models.IntegerField()
    quantity = models.IntegerField()
    date = models.DateTimeField( auto_now=False, auto_now_add=False)
    class Meta:
        verbose_name = ("ImportedProduct")
        verbose_name_plural = ("ImportedProducts")

    def get_absolute_url(self):
        return reverse("ImportedProduct_detail", kwargs={"pk": self.pk})
class ProductInStock(models.Model) :
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    importPrice = models.IntegerField()
class OrderNotification(models.Model) : 
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    description = models.TextField()
class OrderNotificationAccount(models.Model) :
    person = models.ForeignKey(Person, on_delete=models.CASCADE) 
    isRead = models.BooleanField()
    orderNotification = models.ForeignKey(OrderNotification, on_delete=models.CASCADE)
class OrderFeedback(models.Model) : 
    isFeedback = models.BooleanField(default=False)
    quality = models.IntegerField( choices=[(1, "Terrible"), (2, "Bad"), (3, "OK"), (4, "Good"), (5, "Awesome")])
    action = models.IntegerField(choices=[(1, "Trả hàng"), (2, "Không")])
    content = models.TextField()
    order = models.ForeignKey(Order , on_delete=models.CASCADE, null=True)

product/models.py
from django.db import models
from user.models import Account, Person
# Create your models here.
class Category(models.Model) : 
    query = models.CharField(max_length=50)
    type = models.CharField(max_length=200)
class Product(models.Model) : 
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=200, default="")
    price  = models.BigIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
class Supplier(models.Model) :
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.EmailField()
    description =models.TextField(default="", max_length=200)
class Comment(models.Model) :
    content = models.CharField(max_length=500)
    created = models.DateTimeField(blank = True, auto_now_add=True)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, default="2")
class Rate(models.Model) : 
    rate = models.BigIntegerField()
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    created = models.DateTimeField(blank = True, auto_now_add=True)
class Cart(models.Model) : 
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
class SelectedProduct(models.Model) : 
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

order/views.py
from django.contrib import messages
from django.utils import timezone
from order.models import ProductInStock, Order, OrderLine, Shipping, OrderNotification, OrderNotificationAccount , Warehouse, ImportedProduct
from django.shortcuts import redirect, render
from product.models import Category, Product, Supplier
from user.models import Person
# Create your views here.
def index(request) :
    try :
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
        q = request.GET.get('q')
        products = Product.objects.filter(name__contains=q)
        return render(request, 'page/index.html', {'products' : products, "person" : person})
    except KeyError: 
        return redirect('/user/login/')
    except : 
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
        products = Product.objects.all()
        return render(request, 'page/index.html', {'products' : products, "person" : person})
def update_item(request, id) :
    try :
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
    except : 
        return redirect('/user/login/')
    if request.method == 'GET' :
        product = Product.objects.get(id = id)
        categories = Category.objects.all()
        return render(request, 'update-item/index.html', {'product' : product, 'categories' : categories})
    if request.method == 'POST' :
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        category = request.POST.get('category')
        Product.objects.filter(id = id).update(name = name, price = price, description = description, category = Category(id = category))
        return redirect('/employee/')
def add_item(request) :
    try :
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
    except : 
        return redirect('/user/login/')
    if request.method == 'GET' :
        categories = Category.objects.all()
        return render(request, 'create-item/index.html', {'categories' : categories})
    if request.method == 'POST' :
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        category = request.POST.get('category')
        Product.objects.create(name = name, price = price, description = description, category = Category(id = category))
        next =request.GET.get('next')
        return redirect(next or '/employee/')
def delete_item(request, id) :
    try :
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
    except : 
        return redirect('/user/login/')
    product  = Product(id = id)
    Product.delete(product)
    return redirect('/employee/')
def orders(request) : 
    try :
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
    except : 
        return redirect('/user/login/')
    shipping = Shipping.objects.filter(shipStatus = 0)
    print(Shipping.objects.filter(shipStatus = 0))
    orders = Order.objects.filter(shipping__in = shipping)
    return render(request, 'page/orders.html', {"orders" : orders})
def detailed_order(request, id) :
    try :
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
    except : 
        return redirect('/user/login/')
    order= Order.objects.get(id = id)
    products = OrderLine.objects.filter(order_id = order.id)
    return render(request, 'page/detailed-order.html', {"order" : order, "products" : products}) 
def shipping_orders(request) : 
    if request.method == 'GET' : 
        try :
            person = Person.objects.get(id = request.COOKIES["person_id"])
            if person.account.role == 0 :
                messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
                return redirect('/')
        except : 
            return redirect('/user/login/')
        shipping = Shipping.objects.filter(shipStatus = 1)
        orders = Order.objects.filter(shipping__in = shipping)
        return render(request, 'page/shipping-orders.html', {"orders" : orders})
    if request.method == "POST" : 
        orderId = request.POST.get('orderId')
        order = Order.objects.get(id = orderId)
        Shipping.objects.filter(id = order.shipping.id).update(shipStatus = 2)
        orderNoti = OrderNotification.objects.create(order_id = order.id, description="Đơn hàng đã được giao thành công!!")
        orderNoti.save()
        ona = OrderNotificationAccount.objects.create(person_id = order.person_id, orderNotification_id = orderNoti.id, isRead = False)
        return redirect('./')
def shipped_change(request, id) : 
    try :
        person = Person.objects.get(id = request.COOKIES["person_id"])
        if person.account.role == 0 :
            messages.warning(request, message="Đường dẫn không đúng hoặc không có quyền truy nhập")
            return redirect('/')
        order = Order.objects.get(id = id)
        Shipping.objects.filter(id = order.shipping.id).update(shipStatus = 1)
        orderNoti = OrderNotification.objects.create(order_id = order.id, description="Đơn hàng của bạn đang được vận chuyển. Vui lòng đợi cho tới khi nhận được cuộc gọi của người giao hàng")
        orderNoti.save()
        ona = OrderNotificationAccount.objects.create(person_id = order.person_id, orderNotification_id = orderNoti.id, isRead = False)
        ona.save()
        return redirect('/employee/orders/')
    except : 
        return redirect('/user/login/')
def import_item(request) : 
    if request.method == 'GET' : 
        products = Product.objects.all()
        warehouses = Warehouse.objects.all()
        suppliers = Supplier.objects.all()
        return render(request, 'page/import-item.html', {"products" : products, "warehouses" : warehouses, "suppliers" : suppliers})
    if request.method == "POST" : 
        productid = request.POST.get('product')
        warehouseid = request.POST.get('warehouse')
        price = request.POST.get('price')
        quantity = request.POST.get('quantity')
        supplierid = request.POST.get('supplier')
        importedProduct = ImportedProduct.objects.create(product_id = productid, supplier_id = supplierid, warehouse_id = warehouseid, importPrice = price, quantity= quantity, date = timezone.now())
        importedProduct.save()
        try : 
            productInStock = ProductInStock.objects.get(product_id = productid, warehouse_id = warehouseid)
            ProductInStock.objects.filter(id = productInStock.id).update(quantity = productInStock.quantity + quantity)
        except : 
            ProductInStock.objects.create(product_id = productid, warehouse_id = warehouseid, importPrice = price, quantity = quantity)
        return redirect('/employee/') 

product/templates/order/create-order.html
{% extends '../layout.html' %} {% block content %}
<div class="container">
  <div class="row d-flex justify-content-center">
    <form class="w-50" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label>First Name</label>
        <input
          class="form-control"
          type="text"
          value="{{person.fullName.firstName}}"
          readonly
        />
      </div>
      <div>
        <label>Middle Name</label>
        <input
          class="form-control"
          type="text"
          value="{{person.fullName.middleName}}"
          readonly
        />
      </div>
      <div>
        <label>Last Name</label>
        <input
          class="form-control"
          type="text"
          value="{{person.fullName.lastName}}"
          readonly
        />
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <td>Product</td>
            <td>Quantity</td>
            <td>Price</td>
          </tr>
        </thead>
        <tbody>
          {% if product %}
          <tr>
            <td>{{product.name}}</td>
            <td>1</td>
            <td>{{product.price}}</td>
          </tr>
          {% endif %} {% if products %} {% for product in products %}
          <tr>
            <td>{{product.product.name}}</td>
            <td>{{product.quantity}}</td>
            <td>{{product.product.price}}</td>
          </tr>
          {% endfor %} {% endif %}
        </tbody>
      </table>
      <div>
        <label>Tổng</label>
        <input
          class="form-control"
          name="total"
          value="{% if total%} {{total}} {% endif %}{% if not total %} {{product.price}} {% endif %}"
          readonly
        />
      </div>
      <div>
        <label>Xã</label>
        <input class="form-control" value="{{person.address.wards}}" readonly />
      </div>
      <div>
        <label>Quận/Huyện</label>
        <input
          class="form-control"
          value="{{person.address.district}}"
          readonly
        />
      </div>
      <div>
        <label>Tỉnh/Thành phố</label>
        <input
          class="form-control"
          value="{{person.address.province}}"
          readonly
        />
      </div>
      <div>
        <label for="paymentmethod"> Phương thức thanh toán</label>
        <select class="form-control" name="paymentmethod">
          <option value="COD">COD</option>
          <option value="BANK">BANK</option>
        </select>
      </div>
      <div class="d-flex justify-content-around mt-3">
        <button class="btn btn-success" type="submit">Submit</button>
        <a class="btn btn-light" href="/">Trang chủ</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

product/templates/order/detail-feedback.html
{% extends '../layout.html' %} {% block content %}
<div class="container">
  <div class="row d-flex justify-content-center align-items-center">
    <div class="col-5">
      <form>
        <h2>Bạn đang phản hồi cho Order</h1>
        <div class="form-group mt-2">           
          <label>ID : </label>
          <input class='form-control' type='text' value="{{order.id}}" readonly>
        </div>
        <div class="form-group mt-2">           
          <label>Ngày : </label>
          <input class='form-control' type='text' value="{{order.date}}" readonly>
        </div>
        <div class="form-group mt-2">           
          <label>Đánh giá chất lượng : </label>
          <input value={{orderfeedback.get_quality_display}}>
        </div>
        <div class="form-group mt-2">           
          <label>Yêu cầu : </label>
          <input value={{orderfeedback.get_action_display}} />
        </div>
        <div class="form-group mt-2">            
          <label>Mô tả về lỗi phản ánh : </label>
          <textarea
            row="20"
            style="height: 200px"
            class="form-control mt-2"
            name="content"
            placeholder="Nhập nội dung phản ánh..."
          >{{orderfeedback.content}}</textarea>
        </div>
        <a class="btn btn-primary mt-4" href='/' type="submit">Trang chủ</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

product/templates/order/detail-order.html
{% extends '../layout.html' %} {% block content %}
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-5">
      <div>
        <label>Họ tên</label>
        <input
          class="form-control"
          type="text"
          value="{{person.fullName.firstName}} {{person.fullName.middleName}} {{person.fullName.lastName}}"
          readonly
        />
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <td>Product</td>
            <td>Quantity</td>
            <td>Price</td>
          </tr>
        </thead>
        <tbody>
          {% for orderLine in orderLines %}
          <tr>
            <td>{{orderLine.product.name}}</td>
            <td>{{orderLine.quantity}}</td>
            <td>{{orderLine.product.price}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div>
        <label>Tổng tiền</label>
        <input
          class="form-control"
          name="total"
          value="{{order.payment.amount}}"
          readonly
        />
      </div>
      <div>
        <label for="">Địa chỉ giao hàng</label>
        <input
          class="form-control"
          value="Xã {{person.address.wards}} - Quận(Huyện) {{person.address.district}} - Tỉnh(TP) {{person.address.province}}"
          readonly
        />
      </div>
      <div>
        <label for="">Phương thức thanh toán</label>
        <input
          class="form-control"
          value="{{order.payment.paymentMethod}}"
          readonly
        />

        <div>
          <label for="">Ngày đặt</label>
          <input class="form-control" value="{{order.date}}" readonly />
        </div>
        <div class="mt-2">
          {% if order.shipping.shipStatus == 2 %} {% if ofid %}
          <p>
            Bạn đã phản hồi order này, click vào
            <a href="/detail-feedback/{{ofid}}/">đây</a> để xem phản hồi.
          </p>
          {% endif %} {% if not ofid %}
          <p>
            Bạn đã nhận được hàng, click vào
            <a href="/feedback-order/{{order.id}}/">đây</a> để phản hồi.
          </p>
          {% endif %} {% endif%} {% if order.shipping.shipStatus != 2 %}

          <label for="">Trạng thái giao hàng</label>
          <input
            class="form-control"
            value="{{order.shipping.get_shipStatus_display}}"
            readonly
          />
          {% endif %}
        </div>
        <div class="d-flex justify-content-around mt-2">
          <a class="btn btn-primary" href="/">Trang chủ</a>
          <a class="btn btn-light" href="/orders/">Quay lại</a>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

product/templates/order/feedback-order.html
{% extends '../layout.html' %} {% block content %}
<div class="container">
  <div class="row d-flex justify-content-center align-items-center">
    <div class="col-5">
      <form method="POST">
      {% csrf_token %}
        <h2>Bạn đang phản hồi cho Order</h1>
        <div class="form-group mt-2">           
          <label>ID : </label>
          <input class='form-control' type='text' value="{{order.id}}" readonly>
        </div>
        <div class="form-group mt-2">           
          <label>Ngày : </label>
          <input class='form-control' type='text' value="{{order.date}}" readonly>
        </div>
        <div class="form-group mt-2">           
          <label>Đánh giá chất lượng : </label>
          <select class='form-control' name='quality'>
            <option value='1'>Rất tệ</option>
            <option value='2'>Tệ</option>
            <option value='3'>Ổn</option>
            <option value='4'>Tốt</option>
            <option selected value='5'>Rất tốt</option>
          </select>
        </div>
        <div class="form-group mt-2">           
          <label>Yêu cầu : </label>
          <select class='form-control' name='action'>
            <option value='1'>Trả hàng, hoàn tiền</option>
            <option selected value='2'>Không yêu cầu</option>
          </select>
        </div>
        <div class="form-group mt-2">            
          <label>Mô tả về lỗi phản ánh : </label>
          <textarea
            row="20"
            style="height: 200px"
            class="form-control mt-2"
            name="content"
            placeholder="Nhập nội dung phản ánh..."
          ></textarea>
        </div>
        <button class="btn btn-primary mt-4" type="submit">Gửi phản ánh</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

product/templates/order/view-order.html
{% extends '../layout.html' %}
{% block content %} 
<table class="table table-hover">
  <tr>
     <th>ID</th>
     <th>Order</th>
     <th>Created</th>
     <th>Amount</th>
     <th>Status</td>
     <th>Action</td>
   </tr>
   {% for order in orders %}
   <tr>
     <td>{{order.id}}</td>
     <td>#{{order.id}}</td>
     <td>{{order.date}}</td>
     <td>{{order.payment.amount}}</td>
     <td>{{order.shipping.get_shipStatus_display}}</td>
     <td><a class='btn btn-success' href='/order/{{order.id}}'>Detail</a></td>
   </tr>
   {% endfor %}
</table>
{% endblock %}